# This is a the workflow file for Recharge-master Service
name: Recharge-master Service

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Environment files.
env:
  # PROJECT_ID: ${{ secrets.PROJECT_ID }}
  RUN_REGION: europe-west3
  SERVICE_NAME: recharge-master

jobs:
  pullFile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Pull File from S3 Bucket
        run: |
          aws s3 cp s3://recharge-master/main/recharge-master-main ./.env